### ISSUE TITLE
Update bevy_aseprite_derive dependency

### ISSUE THREAD

**Issue by yulnr** [lerouxrgd/bevy_mod_aseprite#1]
Hey, could we upgrade the version of `bevy_aseprite_derive` to `0.3.1`?
I'm using this crate and I'm the need for path prefixes when loading the resources.
That was solved in `bevy_aseprite_derive` a while back but those changes were just released now.
You can read more about it here https://github.com/mdenchev/bevy_aseprite/issues/11
Thanks!

**Comment by lerouxrgd** [comment]
Hello, I have published version `0.4.1` with dependency `bevy_aseprite_derive` updated as you mentioned.
Thanks for bringing it to my attention !

**Comment by yulnr** [comment]
Awesome, thanks!
