### ISSUE TITLE
Licenseing issues

### ISSUE THREAD

**Issue by noxware** [lerouxrgd/bevy_mod_aseprite#4]
The README says this is a fork of [mdenchev/bevy\_aseprite](https://github.com/mdenchev/bevy_aseprite) which doesn't have a license file. So it falls under this:

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.
>
> [Source](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license)

So as far as I understand, this repo can't be APACHE/MIT licensed.

**Comment by lerouxrgd** [comment]
As you can see [here](https://github.com/mdenchev/bevy_aseprite/blob/main/Cargo.toml#L7) it is licensed under `MIT OR Apache-2.0`. Having a license is required for being published on [crates.io](https://crates.io/crates/bevy_aseprite), which is the case for `mdenchev/bevy_aseprite`.

Note also that `mdenchev/bevy_aseprite` says itself that it's a fork of [TheNeikos/bevy_spicy_aseprite](https://github.com/TheNeikos/bevy_spicy_aseprite) which is also licensed under `MIT OR Apache-2.0` (see [here](https://github.com/TheNeikos/bevy_spicy_aseprite/blob/master/Cargo.toml#L7)).

**Comment by noxware** [comment]
TIL:

> Having a license is required for being published on [crates.io](https://crates.io/crates/bevy_aseprite)

Nice, you're right, my bad.
