### ISSUE TITLE
Possibly add AsepriteAnimation::current_tag

### ISSUE THREAD

**Issue by iulianR** [lerouxrgd/bevy_mod_aseprite#5]
Hello,

Would it make sense to add a `current_tag()` API to `AsepriteAnimation`? I wanted to avoid updating `AsepriteAnimation` in a system if it already exists with my desired tag, but there is currently no way to retrieve the tag of the current animation.

Thank you!

**Comment by lerouxrgd** [comment]
Hello,

I added `pub fn tag(&self) -> Option<&str>` to `Animation` in `0.7.1`.

**Comment by iulianR** [comment]
Looking good - thank you!
